# Generated by Django 3.2.3 on 2021-05-17 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_type', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'certificate',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'department',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'faculty',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grad_level', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'grade',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'school',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('graduation_year', models.IntegerField()),
                ('certificate_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.certificate')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.department')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.grade')),
            ],
            options={
                'verbose_name_plural': 'student',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='professor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.faculty'),
        ),
    ]
